/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CinemaDataBase.BancoFilme;
import CinemaDataBase.BancoPropaganda;
import cinema.Filme;
import cinema.Propaganda;
import cinema.User;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JDesktopPane;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

/**
 *
 * @author lamp
 */
public class CadastrarPropaganda extends javax.swing.JInternalFrame {
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	/**
     * Creates new form CadastrarPropaganda
     */
    private User usuario;
    private JMenuItem menuCadastroPropaganda;
    private JDesktopPane jDesktopPane1;
    private JMenuItem menuExibirFilmes;
    
    CadastrarPropaganda(JMenuItem jMenuItem3,JMenuItem jMenuItem11, User usuario, JDesktopPane painel) {
        initComponents();
        this.usuario=usuario;
        this.menuCadastroPropaganda=jMenuItem3;
        this.jDesktopPane1 = painel;
        this.menuExibirFilmes=jMenuItem3;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextFieldAnunciante = new javax.swing.JTextField();
        jLabelFilme = new javax.swing.JLabel();
        jButtonExibirFilmes = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        jLabel1.setText("Anunciante:");

        jLabelFilme.setText("________________________");

        jButtonExibirFilmes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Search.png"))); // NOI18N
        jButtonExibirFilmes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonExibirFilmesActionPerformed(evt);
            }
        });

        jButton1.setText("Cadastrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Cancelar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel2.setText("Filme:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldAnunciante, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelFilme)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonExibirFilmes, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(52, 52, 52)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldAnunciante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButtonExibirFilmes)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabelFilme)
                        .addComponent(jLabel2)))
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        dispose();
        menuCadastroPropaganda.setEnabled(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String anunciante = jTextFieldAnunciante.getText();
        String id = jLabelFilme.getText().split(" / ")[1];
        Filme filme = new BancoFilme().getObject(id);
        Propaganda propaganda = new Propaganda(anunciante, filme, usuario);
        new BancoPropaganda().saveObject(propaganda);
        JOptionPane.showMessageDialog(null, "Propaganda Cadastrada com sucesso!");
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonExibirFilmesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonExibirFilmesActionPerformed
        ExibirFilmes exibir = new ExibirFilmes(menuExibirFilmes, jLabelFilme);//passar o Menu para o construtor
        jDesktopPane1.add(exibir);
        menuExibirFilmes.setEnabled(false);
        exibir.setVisible(true);
    }//GEN-LAST:event_jButtonExibirFilmesActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonExibirFilmes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelFilme;
    private javax.swing.JTextField jTextFieldAnunciante;
    // End of variables declaration//GEN-END:variables
}
