/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CinemaDataBase.BancoFilme;
import cinema.Filme;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.table.DefaultTableModel;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 *
 * @author lamp
 */
public class ExibirFilmes extends javax.swing.JInternalFrame {

    /**
     * Creates new form ExibirFilmes
     */
    ArrayList<Filme> filmes;
    private DefaultTableModel tabelaModelo;
    private JMenuItem menuexibir;
    JLabel jLabelFilme;
    
    /**
     * @wbp.parser.constructor
     */
    public ExibirFilmes(JMenuItem menuexibir) {
        initComponents();
        listagemFilmes();
        this.menuexibir=menuexibir;
        jButton2.setVisible(false);
    }
    
    public ExibirFilmes(JMenuItem menuexibir, JLabel jLabelFilme) {
        initComponents();
        listagemFilmes();
        this.menuexibir=menuexibir;
        this.jLabelFilme = jLabelFilme;
    }
    public ExibirFilmes(JMenuItem menuexibir,ArrayList<Filme> filmes) {
        initComponents();
        listagemFilmes();
        this.menuexibir=menuexibir;
       // this.jLabelFilme = jLabelFilme;
        this.filmes=filmes;
    }
    
    private void listagemFilmes(){
        tabelaModelo = (DefaultTableModel) jTableModelo.getModel();
        filmes = new BancoFilme().searchObjects();
       
        for (Filme qualquer : filmes) {
            tabelaModelo.addRow(new Object[]{qualquer.getId(),qualquer.getTituloPortugues(),qualquer.getGenero(),qualquer.getTipo(),qualquer.getClassificacaoindicativa()});
        }
    }

    /**
     * This method is lled from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableModelo = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("FILMES CASTRADOS");

        jTableModelo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Titulo ", "Genero", "Tipo", "Classificação"
            }
        ));
        jScrollPane1.setViewportView(jTableModelo);

        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Selecionar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        layout.setHorizontalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        			.addGroup(layout.createParallelGroup(Alignment.LEADING)
        				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        					.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 380, GroupLayout.PREFERRED_SIZE)
        					.addContainerGap())
        				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        					.addComponent(jButton2, GroupLayout.PREFERRED_SIZE, 121, GroupLayout.PREFERRED_SIZE)
        					.addGap(26)
        					.addComponent(jButton1, GroupLayout.PREFERRED_SIZE, 127, GroupLayout.PREFERRED_SIZE)
        					.addGap(22))
        				.addGroup(Alignment.TRAILING, layout.createSequentialGroup()
        					.addComponent(jLabel1)
        					.addGap(95))))
        );
        layout.setVerticalGroup(
        	layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(layout.createSequentialGroup()
        			.addGap(25)
        			.addComponent(jLabel1)
        			.addGap(18)
        			.addComponent(jScrollPane1, GroupLayout.PREFERRED_SIZE, 144, GroupLayout.PREFERRED_SIZE)
        			.addPreferredGap(ComponentPlacement.RELATED)
        			.addGroup(layout.createParallelGroup(Alignment.BASELINE)
        				.addComponent(jButton1)
        				.addComponent(jButton2))
        			.addContainerGap(18, Short.MAX_VALUE))
        );
        getContentPane().setLayout(layout);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        dispose();
        menuexibir.setEnabled(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int linhaSelecionada = jTableModelo.getSelectedRow();
        String titulo =(String) tabelaModelo.getValueAt(linhaSelecionada, 1);
        int id =(int) tabelaModelo.getValueAt(linhaSelecionada, 0);
        jLabelFilme.setText(titulo+" / "+id);
        dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableModelo;
    // End of variables declaration//GEN-END:variables
}
