/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CinemaDataBase.BancoFilme;
import cinema.Filme;
import cinema.User;

import java.awt.Component;
import java.awt.Image;
import java.awt.Toolkit;
import java.net.URL;
import java.util.ArrayList;

import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JInternalFrame;
import javax.swing.JLabel;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;

import se.Fato;
import se.ListadeFilmes;
import se.MotorInferencia;
import se.fatos.Classificacao;

import java.awt.event.ActionListener;
import java.awt.event.ActionEvent;

/**
 *
 * @author lamp
 */
public class JanelaPrincipal extends javax.swing.JFrame {
    /**
     * Creates new form JanelaPrincipal
     */

    private User usuario;
    private JanelaPrincipal janela;
    public JanelaPrincipal(){
        setLocationRelativeTo(null); 
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/IMAGES/Icon.png")).getImage());
        JanelaLogin a = new JanelaLogin(this);
        jMenuBar1.setVisible(false);//henrique e rafael axei melhor assim e vcs?
        jDesktopPane1.add(a);
        a.setVisible(true);

    }
    
    public JanelaPrincipal(User usuario) {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("/IMAGES/Icon.png")).getImage());  
        setExtendedState(MAXIMIZED_BOTH);
        this.usuario=usuario;
        setTitle("Cinetec - Bem Vindo "+ usuario.getLogin());
        if (!(usuario.getLogin().equals("admin"))){
            jMenuItem6.setEnabled(false);
            jMenuItem23.setEnabled(false);
            jMenuItem32.setEnabled(false);
        }
    }

       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu5 = new javax.swing.JMenu();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem24 = new javax.swing.JMenuItem();
        jMenuItem27 = new javax.swing.JMenuItem();
        jMenuItem33 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenuItem18 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem19 = new javax.swing.JMenuItem();
        jMenuItem20 = new javax.swing.JMenuItem();
        jMenuItem21 = new javax.swing.JMenuItem();
        jMenuItem22 = new javax.swing.JMenuItem();
        jMenuItem23 = new javax.swing.JMenuItem();
        jMenuItem25 = new javax.swing.JMenuItem();
        jMenuItem26 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenuItem28 = new javax.swing.JMenuItem();
        jMenuItem29 = new javax.swing.JMenuItem();
        jMenuItem30 = new javax.swing.JMenuItem();
        jMenuItem31 = new javax.swing.JMenuItem();
        jMenuItem32 = new javax.swing.JMenuItem();
        jMenuItem34 = new javax.swing.JMenuItem();
        jMenuItem35 = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CineTec");

        jDesktopPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jDesktopPane1.setToolTipText("");

        jMenu1.setText("Sistema");

        jMenuItem15.setText("Permissões Usuario");
        jMenu1.add(jMenuItem15);

        jMenuItem24.setText("Fazer Logof");
        jMenuItem24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem24ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem24);

        jMenuItem27.setText("Efetuar Vendas");
        jMenuItem27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem27ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem27);

        jMenuItem33.setText("Devolver Ingresso");
        jMenuItem33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem33ActionPerformed(evt);
            }
        });
        
        final JMenuItem mntmSugerirFilme = new JMenuItem("Sugerir Filme");
        mntmSugerirFilme.addActionListener(new ActionListener() {
        	public void actionPerformed(ActionEvent e) {
        		String consulta=(new MotorInferencia().inferir(new ListadeFilmes())).getValor();
        		System.out.println(consulta);
        		ArrayList<Filme> filmes=new BancoFilme().searchObjects(consulta);
        		String f=new String();
        		for (Filme filme : filmes) {
					f=f+filme.getTituloPortugues()+" "+filme.getClassificacaoindicativa()+" "+filme.getGenero()+"\n";
				}
        		JOptionPane.showMessageDialog(null, f);
        	//	new ExibirFilmes(mntmSugerirFilme, filmes);
        		
        	}
        });
        jMenu1.add(mntmSugerirFilme);
        jMenu1.add(jMenuItem33);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Cadastrar");

        jMenuItem2.setText("Sessão");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem2);

        jMenuItem3.setText("Filme");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem3);

        jMenuItem4.setText("Sala");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem4);

        jMenuItem5.setText("Cliente");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem5ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem5);

        jMenuItem6.setText("Funcionário");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem6ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem6);

        jMenuItem8.setText("Usuário");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem8);

        jMenuItem7.setText("Propaganda");
        jMenuItem7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem7ActionPerformed(evt);
            }
        });
        jMenu2.add(jMenuItem7);

        jMenuItem9.setText("Cinema");
        jMenu2.add(jMenuItem9);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Exibir");

        jMenuItem10.setText("Sessão");
        jMenuItem10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem10ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem10);

        jMenuItem11.setText("Filme");
        jMenuItem11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem11ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem11);

        jMenuItem12.setText("Sala");
        jMenuItem12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem12ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem12);

        jMenuItem13.setText("Cliente");
        jMenuItem13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem13ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem13);

        jMenuItem14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGES/Profile.png"))); // NOI18N
        jMenuItem14.setText("Funcionário");
        jMenuItem14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem14ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem14);

        jMenuItem16.setText("Usuário");
        jMenu3.add(jMenuItem16);

        jMenuItem17.setText("Propaganda");
        jMenu3.add(jMenuItem17);

        jMenuItem18.setText("Cinema");
        jMenu3.add(jMenuItem18);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Alterar");

        jMenuItem19.setText("Sessão");
        jMenu4.add(jMenuItem19);

        jMenuItem20.setText("Filme");
        jMenu4.add(jMenuItem20);

        jMenuItem21.setText("Sala");
        jMenu4.add(jMenuItem21);

        jMenuItem22.setText("Cliente");
        jMenu4.add(jMenuItem22);

        jMenuItem23.setText("Funcionário");
        jMenu4.add(jMenuItem23);

        jMenuItem25.setText("Usuário");
        jMenu4.add(jMenuItem25);

        jMenuItem26.setText("Propaganda");
        jMenu4.add(jMenuItem26);

        jMenuItem1.setText("Cinema");
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        jMenu6.setText("Excluir");

        jMenuItem28.setText("Sessão");
        jMenu6.add(jMenuItem28);

        jMenuItem29.setText("Filme");
        jMenu6.add(jMenuItem29);

        jMenuItem30.setText("Sala");
        jMenu6.add(jMenuItem30);

        jMenuItem31.setText("Cliente");
        jMenu6.add(jMenuItem31);

        jMenuItem32.setText("Funcionário");
        jMenu6.add(jMenuItem32);

        jMenuItem34.setText("Usuário");
        jMenu6.add(jMenuItem34);

        jMenuItem35.setText("Propaganda");
        jMenu6.add(jMenuItem35);

        jMenuBar1.add(jMenu6);

        jMenu7.setText("Ajuda");
        jMenuBar1.add(jMenu7);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jDesktopPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 657, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public  void poximaJanela(JInternalFrame internal){
        this.jDesktopPane1.add(internal);
        internal.setVisible(true);
    }
    
    
       
    private void jMenuItem6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem6ActionPerformed
        CadastrarFuncionario funcionario = new CadastrarFuncionario(jMenuItem6,usuario);//passar o Menu para o construtor

        jDesktopPane1.add(funcionario);
        jMenuItem6.setEnabled(false);
        funcionario.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem6ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        CadastrarUsuario usuario = new CadastrarUsuario(jMenuItem8);//passar o Menu para o construtor
        jDesktopPane1.add(usuario);
        jMenuItem8.setEnabled(false);
        usuario.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    private void jMenuItem5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem5ActionPerformed
        CadastrarCliente telacliente = new CadastrarCliente(jMenuItem5,usuario);//passar o Menu para o construtor
        jDesktopPane1.add(telacliente);
        jMenuItem5.setEnabled(false);
        telacliente.setVisible(true);
    }//GEN-LAST:event_jMenuItem5ActionPerformed

    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
  
        CadastrarFilme filme = new CadastrarFilme(jMenuItem3,usuario);//passar o Menu para o construtor
        jDesktopPane1.add(filme);
        jMenuItem3.setEnabled(false);
        filme.setVisible(true);
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jMenuItem14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem14ActionPerformed
     ExibirFuncionarios exibir = new ExibirFuncionarios(jMenuItem4);
     jDesktopPane1.add(exibir);
     jMenuItem4.setEnabled(false);
     exibir.setVisible(true);
    }//GEN-LAST:event_jMenuItem14ActionPerformed

    private void jMenuItem13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem13ActionPerformed
     ExibirCliente exibir = new ExibirCliente(jMenuItem13);
     jDesktopPane1.add(exibir);
     jMenuItem13.setEnabled(false);
     exibir.setVisible(true);
     
     
 
    }//GEN-LAST:event_jMenuItem13ActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        CadastrarSala sala = new CadastrarSala(jMenuItem4,usuario);//passar o Menu para o construtor
        jDesktopPane1.add(sala);
        jMenuItem4.setEnabled(false);
        sala.setVisible(true);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jMenuItem7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem7ActionPerformed
        CadastrarPropaganda propaganda = new CadastrarPropaganda(jMenuItem7,jMenuItem11,usuario, jDesktopPane1);//passar o Menu para o construtor
        jDesktopPane1.add(propaganda);
        jMenuItem7.setEnabled(false);
        propaganda.setVisible(true);
    }//GEN-LAST:event_jMenuItem7ActionPerformed

    private void jMenuItem11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem11ActionPerformed
        ExibirFilmes exibir = new ExibirFilmes(jMenuItem11);//passar o Menu para o construtor
        jMenuItem11.setEnabled(false);
        jDesktopPane1.add(exibir);
        exibir.setVisible(true);
    }//GEN-LAST:event_jMenuItem11ActionPerformed

    private void jMenuItem24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem24ActionPerformed
        dispose();
        new JanelaPrincipal().setVisible(true);
    }//GEN-LAST:event_jMenuItem24ActionPerformed

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        CadastrarSessao sessao = new CadastrarSessao(jMenuItem2,jMenuItem11,usuario, jDesktopPane1);//passar o Menu para o construtor
        jDesktopPane1.add(sessao);
        jMenuItem2.setEnabled(false);
        sessao.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem10ActionPerformed
        ExibirSessoes exibir = new ExibirSessoes(jMenuItem10);
        jDesktopPane1.add(exibir);
        jMenuItem10.setEnabled(false);
        exibir.setVisible(true);
    }//GEN-LAST:event_jMenuItem10ActionPerformed

    private void jMenuItem12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem12ActionPerformed
        ExibirSalas exibir = new ExibirSalas(jMenuItem12);//passar o Menu para o construtor
        jMenuItem12.setEnabled(false);
        jDesktopPane1.add(exibir);
        exibir.setVisible(true);
    }//GEN-LAST:event_jMenuItem12ActionPerformed

    private void jMenuItem27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem27ActionPerformed
        Vendas vendas = new Vendas(jMenuItem27,usuario,jDesktopPane1);
        jMenuItem27.setEnabled(false);
        jDesktopPane1.add(vendas);
        vendas.setVisible(true);
    }//GEN-LAST:event_jMenuItem27ActionPerformed

    private void jMenuItem33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem33ActionPerformed
        DevolverIngresso devolver = new DevolverIngresso(jMenuItem33,usuario,jDesktopPane1);
        jDesktopPane1.add(devolver);
        jMenuItem33.setEnabled(false);
        devolver.setVisible(true);
        
    }//GEN-LAST:event_jMenuItem33ActionPerformed
   
    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem18;
    private javax.swing.JMenuItem jMenuItem19;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem20;
    private javax.swing.JMenuItem jMenuItem21;
    private javax.swing.JMenuItem jMenuItem22;
    private javax.swing.JMenuItem jMenuItem23;
    private javax.swing.JMenuItem jMenuItem24;
    private javax.swing.JMenuItem jMenuItem25;
    private javax.swing.JMenuItem jMenuItem26;
    private javax.swing.JMenuItem jMenuItem27;
    private javax.swing.JMenuItem jMenuItem28;
    private javax.swing.JMenuItem jMenuItem29;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem30;
    private javax.swing.JMenuItem jMenuItem31;
    private javax.swing.JMenuItem jMenuItem32;
    private javax.swing.JMenuItem jMenuItem33;
    private javax.swing.JMenuItem jMenuItem34;
    private javax.swing.JMenuItem jMenuItem35;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    // End of variables declaration//GEN-END:variables
@Override
public void setLocationRelativeTo(Component c){
    setLocation(540, 200);
}
}
